repos:
- repo: local
  hooks:
  # - id: black
  #   name: Black
  #   entry: poetry run black --quiet
  #   language: system
  #   types: [python]
  #   require_serial: true
  
  # - id: yapf
  #   name: YAPF
  #   entry: poetry run yapf --recursive --in-place .
  #   language: system
  #   types: [python]
  #   require_serial: true

  - id: pylint
    name: Pylint
    entry: poetry run pylint .
    language: system
    types:
      - python
    require_serial: true
    
  - id: ruff
    name: ruff
    entry: poetry run ruff check . --fix
    language: system
    types:
      - python
    require_serial: true
