name: tests

run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on:
  pull_request:
    branches:
      - master

jobs:
  Run-Tests:
    runs-on: ubuntu-22.04
    container:
      image: catthehacker/ubuntu:act-22.04
    env:
      VK_USER_TOKEN: ${{ secrets.VK_USER_TOKEN }}
      VK_USER_LOGIN: ${{ secrets.VK_USER_LOGIN }}
      VK_USER_PASSWORD: ${{ secrets.VK_USER_PASSWORD }}
      VK_USER_2FA: ${{ secrets.VK_USER_2FA }}
      VK_USER_ID: ${{ secrets.VK_USER_ID }}
      VK_AUDIO_CLIENT_SECRET: ${{ secrets.VK_AUDIO_CLIENT_SECRET }}
      VK_ARCHIVE_GROUP_TOKEN: ${{ secrets.VK_ARCHIVE_GROUP_TOKEN }}
      VK_ARCHIVE_GROUP_ID: ${{ secrets.VK_ARCHIVE_GROUP_ID }}
      VK_MAIN_GROUP_URL: ${{ secrets.VK_MAIN_GROUP_URL }}
      VK_MAIN_GROUP_TOKEN: ${{ secrets.VK_MAIN_GROUP_TOKEN }}
      VK_MAIN_GROUP_ID: ${{ secrets.VK_MAIN_GROUP_ID }}
      VIDEO_MAX_DURATION: ${{ secrets.VIDEO_MAX_DURATION }}
      ZODB_DB_PATH: ${{ secrets.ZODB_DB_PATH }}
      PYTHONPATH: ${{ secrets.PYTHONPATH }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup ffmpeg
        run: |
          sudo apt update
          apt install ffmpeg -y
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.10
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config installer.max-workers 10
          poetry install
      - name: Test with pytest
        run: |
          mkdir .db
          poetry run python -m pytest
